use async_trait::async_trait;
use luma_application::PasteboardSnapshot;
use serde::Deserialize;
use sha2::{Digest, Sha256};
use std::process::Stdio;
use std::sync::{Mutex, OnceLock};
use tokio::process::Command;

pub use luma_application::{PasteboardError, PasteboardPort as Pasteboard};

/// Uses macOS pasteboard tools. History capture asks a bounded JXA bridge for type metadata so
/// concealed/transient producer flags are honored without linking product Rust crates to AppKit.
pub struct MacPasteboard;

const PRIVATE_PASTEBOARD_TYPES: &[&str] = &[
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
    "com.agilebits.onepassword",
    "com.1password",
];

fn capture_blocked_by_types<T>(types: impl IntoIterator<Item = T>) -> bool
where
    T: AsRef<str>,
{
    types.into_iter().any(|value| {
        PRIVATE_PASTEBOARD_TYPES
            .iter()
            .any(|private| value.as_ref().eq_ignore_ascii_case(private))
    })
}

#[derive(Deserialize)]
struct NativePasteboardSnapshot {
    #[serde(default)]
    types: Vec<String>,
    text: Option<String>,
}

const SNAPSHOT_SCRIPT: &str = r#"ObjC.import("AppKit");
var p = $.NSPasteboard.generalPasteboard;
var v = p.stringForType("public.utf8-plain-text");
JSON.stringify({
  types: ObjC.unwrap(p.types).map(function(x) { return ObjC.unwrap(x); }),
  text: v ? ObjC.unwrap(v) : null
})"#;

fn capture_digest(text: &str) -> [u8; 32] {
    Sha256::digest(text.as_bytes()).into()
}

fn capture_cache() -> &'static Mutex<Option<[u8; 32]>> {
    static CACHE: OnceLock<Mutex<Option<[u8; 32]>>> = OnceLock::new();
    CACHE.get_or_init(|| Mutex::new(None))
}

async fn read_text_with_pbpaste() -> Result<Option<String>, PasteboardError> {
    let out = Command::new("/usr/bin/pbpaste")
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .output()
        .await?;
    if !out.status.success() {
        return Err(PasteboardError::Unavailable(format!(
            "pbpaste exited {}",
            out.status
        )));
    }
    let text = String::from_utf8_lossy(&out.stdout).to_string();
    Ok((!text.is_empty()).then_some(text))
}

async fn read_native_capture_snapshot() -> Result<PasteboardSnapshot, PasteboardError> {
    let Some(preflight_text) = read_text_with_pbpaste().await? else {
        return Ok(PasteboardSnapshot::default());
    };
    let preflight_digest = capture_digest(&preflight_text);
    if capture_cache()
        .lock()
        .expect("pasteboard capture cache lock")
        .as_ref()
        == Some(&preflight_digest)
    {
        return Ok(PasteboardSnapshot {
            text: None,
            capture_allowed: false,
        });
    }

    let output = Command::new("/usr/bin/osascript")
        .args(["-l", "JavaScript", "-e", SNAPSHOT_SCRIPT])
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .output()
        .await?;
    if !output.status.success() {
        return Err(PasteboardError::Unavailable(format!(
            "pasteboard metadata query exited {}",
            output.status
        )));
    }
    let native: NativePasteboardSnapshot = serde_json::from_slice(&output.stdout)
        .map_err(|_| PasteboardError::Unavailable("invalid pasteboard metadata response".into()))?;
    let text = native.text.filter(|value| !value.is_empty());
    if let Some(value) = &text {
        *capture_cache()
            .lock()
            .expect("pasteboard capture cache lock") = Some(capture_digest(value));
    }
    Ok(PasteboardSnapshot {
        text,
        capture_allowed: !capture_blocked_by_types(&native.types),
    })
}

#[async_trait]
impl Pasteboard for MacPasteboard {
    async fn read_text(&self) -> Result<Option<String>, PasteboardError> {
        read_text_with_pbpaste().await
    }

    async fn read_for_capture(&self) -> Result<PasteboardSnapshot, PasteboardError> {
        read_native_capture_snapshot().await
    }

    async fn write_text(&self, text: &str) -> Result<(), PasteboardError> {
        let mut child = Command::new("/usr/bin/pbcopy")
            .kill_on_drop(true)
            .stdin(Stdio::piped())
            .stdout(Stdio::null())
            .stderr(Stdio::piped())
            .spawn()?;
        if let Some(mut stdin) = child.stdin.take() {
            use tokio::io::AsyncWriteExt;
            stdin.write_all(text.as_bytes()).await?;
        }
        let status = child.wait().await?;
        if status.success() {
            Ok(())
        } else {
            Err(PasteboardError::Unavailable(format!(
                "pbcopy exited {status}"
            )))
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    struct MemPb {
        text: tokio::sync::Mutex<Option<String>>,
    }

    #[async_trait]
    impl Pasteboard for MemPb {
        async fn read_text(&self) -> Result<Option<String>, PasteboardError> {
            Ok(self.text.lock().await.clone())
        }
        async fn write_text(&self, text: &str) -> Result<(), PasteboardError> {
            *self.text.lock().await = Some(text.to_string());
            Ok(())
        }
    }

    #[tokio::test]
    async fn mem_roundtrip() {
        let pb = MemPb {
            text: tokio::sync::Mutex::new(None),
        };
        pb.write_text("hi").await.unwrap();
        assert_eq!(pb.read_text().await.unwrap().as_deref(), Some("hi"));
    }

    #[test]
    fn concealed_and_transient_markers_block_history_capture() {
        assert!(capture_blocked_by_types([
            "public.utf8-plain-text",
            "org.nspasteboard.ConcealedType",
        ]));
        assert!(capture_blocked_by_types(["org.nspasteboard.transienttype"]));
        assert!(!capture_blocked_by_types([
            "public.utf8-plain-text",
            "public.html",
        ]));
    }
}
