import Foundation

public enum ClipboardFilter {
    private static let exactBlockedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType"
    ]

    private static let blockedPrefixes = [
        "com.agilebits.",
        "com.1password.",
        "com.lastpass.",
        "com.bitwarden.",
        "com.dashlane.",
        "com.keeper.",
        "com.apple.security."
    ]

    private static let blockedSubstrings = [
        "password",
        "secret",
        "token",
        "secure"
    ]

    public static func shouldSkip(types: [String]) -> Bool {
        types.contains { raw in
            if exactBlockedTypes.contains(raw) { return true }
            let lower = raw.lowercased()
            if blockedPrefixes.contains(where: { lower.hasPrefix($0) }) { return true }
            return blockedSubstrings.contains(where: { lower.contains($0) })
        }
    }

    public static func acceptsText(_ text: String, maxBytes: Int = 100 * 1024) -> Bool {
        !text.isEmpty && text.data(using: .utf8, allowLossyConversion: false)?.count ?? 0 <= maxBytes
    }
}
