import Foundation

public enum ClipboardFilter {
    private static let exactBlockedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType"
    ]

    private static let blockedTypePrefixes = [
        "com.agilebits.",
        "com.1password.",
        "com.lastpass.",
        "com.bitwarden.",
        "com.dashlane.",
        "com.keeper.",
        "com.apple.security."
    ]

    private static let blockedTypeSubstrings = [
        "password",
        "secret",
        "token",
        "secure"
    ]

    private static let publicTextTypes: Set<String> = [
        "public.utf8-plain-text",
        "NSStringPboardType",
        "public.plain-text",
        "public.text",
        "public.html",
        "public.rtf"
    ]

    private static let defaultBlockedBundleIDs: Set<String> = [
        "com.agilebits.onepassword7",
        "com.agilebits.onepassword4",
        "com.agilebits.onepassword",
        "com.1password.1password",
        "com.1password.1password-macos",
        "com.1password.safari",
        "com.bitwarden.desktop",
        "com.dashlane.dashlanephonefinal",
        "com.dashlane.Dashlane",
        "com.keepersecurity.KeeperDesktop",
        "com.lastpass.LastPass",
        "com.apple.keychainaccess"
    ]

    public static func shouldSkip(types: [String]) -> Bool {
        if types.contains(where: { exactBlockedTypes.contains($0) }) {
            return true
        }
        let hasPublicTextType = types.contains { isPublicTextType($0) }
        return types.contains { raw in
            let lower = raw.lowercased()
            if blockedTypePrefixes.contains(where: { lower.hasPrefix($0) }) {
                return true
            }
            if hasPublicTextType {
                return false
            }
            return blockedTypeSubstrings.contains(where: { lower.contains($0) })
        }
    }

    private static func isPublicTextType(_ raw: String) -> Bool {
        publicTextTypes.contains(raw) || raw.hasPrefix("public.text")
    }

    public static func shouldSkipSource(bundleID: String?, ignoredBundleIDs: Set<String> = []) -> Bool {
        guard let bundleID, !bundleID.isEmpty else { return false }
        let blocked = defaultBlockedBundleIDs.union(ignoredBundleIDs)
        return blocked.contains(bundleID)
    }

    public static func looksSensitiveText(_ text: String) -> Bool {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return false }

        if trimmed.contains("-----BEGIN OPENSSH PRIVATE KEY-----")
            || trimmed.contains("-----BEGIN RSA PRIVATE KEY-----")
            || trimmed.contains("-----BEGIN PRIVATE KEY-----") {
            return true
        }

        if looksLikeJWT(trimmed) {
            return true
        }

        if looksLikeAPIKey(trimmed) {
            return true
        }

        if looksLikeCreditCard(trimmed) {
            return true
        }

        return false
    }

    public static func acceptsText(_ text: String, maxBytes: Int = 100 * 1024) -> Bool {
        !text.isEmpty && text.data(using: .utf8, allowLossyConversion: false)?.count ?? 0 <= maxBytes
    }

    private static func looksLikeJWT(_ text: String) -> Bool {
        guard !text.contains(where: \.isWhitespace) else { return false }
        let parts = text.split(separator: ".", omittingEmptySubsequences: false)
        guard parts.count == 3 else { return false }
        guard text.hasPrefix("eyJ") else { return false }
        let body = parts.map(String.init).joined()
        return body.count >= 80 && body.allSatisfy { $0.isLetter || $0.isNumber || $0 == "-" || $0 == "_" || $0 == "." }
    }

    private static func looksLikeAPIKey(_ text: String) -> Bool {
        guard !text.contains(where: \.isWhitespace), text.count >= 20 else { return false }
        if text.hasPrefix("sk-") && text.count >= 32 { return true }
        if text.hasPrefix("AKIA") && text.count == 20 { return true }
        if text.hasPrefix("ghp_") && text.count >= 36 { return true }
        if text.hasPrefix("xoxb-") && text.count >= 40 { return true }
        return false
    }

    private static func looksLikeCreditCard(_ text: String) -> Bool {
        let digits = text.filter(\.isNumber)
        guard (13 ... 19).contains(digits.count), digits.count == text.filter({ $0.isNumber || $0 == " " || $0 == "-" }).count else {
            return false
        }
        return passesLuhn(digits)
    }

    private static func passesLuhn(_ digits: String) -> Bool {
        var sum = 0
        let reversed = digits.reversed().map { Int(String($0)) ?? 0 }
        for (index, digit) in reversed.enumerated() {
            if index.isMultiple(of: 2) {
                sum += digit
            } else {
                let doubled = digit * 2
                sum += doubled > 9 ? doubled - 9 : doubled
            }
        }
        return sum % 10 == 0
    }
}
