//! Built-in modules (personal daily driver).

mod apps;
mod calculator;
mod cancel;
mod clipboard;
mod clipboard_privacy;
mod command_recipes;
mod databases;
mod downloads;
mod fake;
mod git;
mod packages;
mod projects;
mod proxy;
mod quicklinks;
mod records;
mod renewals;
mod runtime;
mod screen_ocr;
mod secrets;
mod shell_history;
mod shortcuts;
mod snippets;
mod ssh;
mod timers;
mod ux;
mod windows;
mod wordbook;

pub use apps::AppsModule;
pub use calculator::CalculatorModule;
pub use clipboard::ClipboardModule;
pub use clipboard_privacy::ClipboardSuppression;
pub use command_recipes::CommandRecipesModule;
pub use databases::DatabasePortalsModule;
pub use downloads::DownloadsModule;
pub use fake::FakeEchoModule;
pub use git::GitModule;
pub use packages::PackagesModule;
pub use projects::ProjectsModule;
pub use proxy::ProxyModule;
pub use quicklinks::QuicklinksModule;
pub use records::RecordsModule;
pub use renewals::RenewalsModule;
pub use runtime::RuntimeModule;
pub use screen_ocr::ScreenOcrModule;
pub use secrets::SecretsModule;
pub use shell_history::ShellHistoryModule;
pub use shortcuts::ShortcutsModule;
pub use snippets::SnippetsModule;
pub use ssh::SshModule;
pub use timers::TimersModule;
pub use windows::{WindowsModule, HUB_WINDOWS_MAX};
pub use wordbook::WordbookModule;
