use luma_domain::{CommandStep, Recipe, RecipeRisk, RecipeScope, RecipeVariant};

fn step(id: &str, label: &str, program: &str, args: &[&str], cwd: &str) -> CommandStep {
    CommandStep {
        id: id.into(),
        label: label.into(),
        program: program.into(),
        args: args.iter().map(|s| (*s).to_string()).collect(),
        cwd: cwd.into(),
        continue_on_error: false,
    }
}

fn git_variant(id: &str, program_args: &[&str], label: &str) -> RecipeVariant {
    RecipeVariant {
        id: id.into(),
        description: "Git repository".into(),
        requires_files: vec![".git".into()],
        requires_directories: vec![],
        requires_commands: vec!["git".into()],
        steps: vec![step(id, label, "git", program_args, "current")],
    }
}

fn recipe(
    id: &str,
    title: &str,
    description: &str,
    tags: &[&str],
    scope: RecipeScope,
    variants: Vec<RecipeVariant>,
) -> Recipe {
    Recipe {
        id: id.into(),
        title: title.into(),
        description: description.into(),
        tags: tags.iter().map(|t| (*t).to_string()).collect(),
        scope,
        risk: RecipeRisk::Safe,
        variants,
        enabled: true,
    }
}

pub fn builtin_recipes() -> Vec<Recipe> {
    vec![
        // Git
        recipe(
            "git-status",
            "Git status",
            "Short branch status",
            &["git"],
            RecipeScope::CurrentProject,
            vec![git_variant(
                "git-status",
                &["status", "--short", "--branch"],
                "git status",
            )],
        ),
        recipe(
            "git-diff",
            "Git diff",
            "Diff stat summary",
            &["git"],
            RecipeScope::CurrentProject,
            vec![git_variant(
                "git-diff",
                &["diff", "--stat"],
                "git diff --stat",
            )],
        ),
        recipe(
            "git-log",
            "Git log",
            "Recent commits oneline",
            &["git"],
            RecipeScope::CurrentProject,
            vec![git_variant(
                "git-log",
                &["log", "--oneline", "-10"],
                "git log",
            )],
        ),
        recipe(
            "git-branch",
            "Git branch",
            "Show current branch",
            &["git"],
            RecipeScope::CurrentProject,
            vec![git_variant(
                "git-branch",
                &["branch", "--show-current"],
                "git branch",
            )],
        ),
        recipe(
            "git-worktree",
            "Git worktree",
            "List worktrees",
            &["git"],
            RecipeScope::CurrentProject,
            vec![git_variant(
                "git-worktree",
                &["worktree", "list"],
                "git worktree list",
            )],
        ),
        // Rust
        recipe(
            "rust-fmt-check",
            "Rust fmt check",
            "Check formatting with cargo fmt",
            &["rust", "fmt"],
            RecipeScope::CurrentProject,
            vec![RecipeVariant {
                id: "rust".into(),
                description: "Rust project".into(),
                requires_files: vec!["Cargo.toml".into()],
                requires_directories: vec![],
                requires_commands: vec!["cargo".into()],
                steps: vec![step(
                    "cargo-fmt",
                    "cargo fmt --check",
                    "cargo",
                    &["fmt", "--all", "--", "--check"],
                    "current",
                )],
            }],
        ),
        recipe(
            "rust-check",
            "Rust check",
            "cargo check workspace",
            &["rust", "check"],
            RecipeScope::CurrentProject,
            vec![RecipeVariant {
                id: "rust".into(),
                description: "Rust project".into(),
                requires_files: vec!["Cargo.toml".into()],
                requires_directories: vec![],
                requires_commands: vec!["cargo".into()],
                steps: vec![step(
                    "cargo-check",
                    "cargo check",
                    "cargo",
                    &["check", "--workspace", "--all-features"],
                    "current",
                )],
            }],
        ),
        recipe(
            "rust-test",
            "Rust test",
            "Run cargo test",
            &["rust", "test"],
            RecipeScope::CurrentProject,
            vec![RecipeVariant {
                id: "rust".into(),
                description: "Rust project".into(),
                requires_files: vec!["Cargo.toml".into()],
                requires_directories: vec![],
                requires_commands: vec!["cargo".into()],
                steps: vec![step(
                    "cargo-test",
                    "cargo test",
                    "cargo",
                    &["test", "--workspace", "--all-features"],
                    "current",
                )],
            }],
        ),
        recipe(
            "rust-clippy",
            "Rust clippy",
            "Run cargo clippy with warnings denied",
            &["rust", "clippy"],
            RecipeScope::CurrentProject,
            vec![RecipeVariant {
                id: "rust".into(),
                description: "Rust project".into(),
                requires_files: vec!["Cargo.toml".into()],
                requires_directories: vec![],
                requires_commands: vec!["cargo".into()],
                steps: vec![step(
                    "cargo-clippy",
                    "cargo clippy",
                    "cargo",
                    &[
                        "clippy",
                        "--workspace",
                        "--all-targets",
                        "--all-features",
                        "--",
                        "-D",
                        "warnings",
                    ],
                    "current",
                )],
            }],
        ),
        // Node
        recipe(
            "node-test",
            "Node test",
            "npm test",
            &["node", "test"],
            RecipeScope::CurrentProject,
            vec![RecipeVariant {
                id: "node".into(),
                description: "Node project".into(),
                requires_files: vec!["package.json".into()],
                requires_directories: vec![],
                requires_commands: vec!["npm".into()],
                steps: vec![step("npm-test", "npm test", "npm", &["test"], "current")],
            }],
        ),
        recipe(
            "node-lint",
            "Node lint",
            "npm run lint when available",
            &["node", "lint"],
            RecipeScope::CurrentProject,
            vec![RecipeVariant {
                id: "node".into(),
                description: "Node project".into(),
                requires_files: vec!["package.json".into()],
                requires_directories: vec![],
                requires_commands: vec!["npm".into()],
                steps: vec![step(
                    "npm-lint",
                    "npm run lint",
                    "npm",
                    &["run", "lint"],
                    "current",
                )],
            }],
        ),
        recipe(
            "node-build",
            "Node build",
            "npm run build",
            &["node", "build"],
            RecipeScope::CurrentProject,
            vec![RecipeVariant {
                id: "node".into(),
                description: "Node project".into(),
                requires_files: vec!["package.json".into()],
                requires_directories: vec![],
                requires_commands: vec!["npm".into()],
                steps: vec![step(
                    "npm-build",
                    "npm run build",
                    "npm",
                    &["run", "build"],
                    "current",
                )],
            }],
        ),
        // Python
        recipe(
            "python-test",
            "Python test",
            "Run pytest",
            &["python", "test"],
            RecipeScope::CurrentProject,
            vec![
                RecipeVariant {
                    id: "pytest-pyproject".into(),
                    description: "Python pyproject".into(),
                    requires_files: vec!["pyproject.toml".into()],
                    requires_directories: vec![],
                    requires_commands: vec!["pytest".into()],
                    steps: vec![step("pytest", "pytest", "pytest", &[], "current")],
                },
                RecipeVariant {
                    id: "pytest-ini".into(),
                    description: "pytest.ini project".into(),
                    requires_files: vec!["pytest.ini".into()],
                    requires_directories: vec![],
                    requires_commands: vec!["pytest".into()],
                    steps: vec![step("pytest", "pytest", "pytest", &[], "current")],
                },
            ],
        ),
        recipe(
            "python-lint",
            "Python lint",
            "Run ruff check",
            &["python", "lint"],
            RecipeScope::CurrentProject,
            vec![RecipeVariant {
                id: "ruff".into(),
                description: "Python with ruff".into(),
                requires_files: vec!["pyproject.toml".into()],
                requires_directories: vec![],
                requires_commands: vec!["ruff".into()],
                steps: vec![step(
                    "ruff-check",
                    "ruff check",
                    "ruff",
                    &["check"],
                    "current",
                )],
            }],
        ),
        // Docker
        recipe(
            "docker-ps",
            "Docker ps",
            "List running containers",
            &["docker"],
            RecipeScope::Global,
            vec![RecipeVariant {
                id: "docker".into(),
                description: "Docker available".into(),
                requires_files: vec![],
                requires_directories: vec![],
                requires_commands: vec!["docker".into()],
                steps: vec![step("docker-ps", "docker ps", "docker", &["ps"], "current")],
            }],
        ),
        recipe(
            "docker-compose-ps",
            "Docker compose ps",
            "List compose services",
            &["docker", "compose"],
            RecipeScope::CurrentProject,
            vec![RecipeVariant {
                id: "compose".into(),
                description: "Docker compose project".into(),
                requires_files: vec!["docker-compose.yml".into()],
                requires_directories: vec![],
                requires_commands: vec!["docker".into()],
                steps: vec![step(
                    "compose-ps",
                    "docker compose ps",
                    "docker",
                    &["compose", "ps"],
                    "current",
                )],
            }],
        ),
        recipe(
            "docker-compose-logs",
            "Docker compose logs",
            "Tail compose logs",
            &["docker", "compose", "logs"],
            RecipeScope::CurrentProject,
            vec![RecipeVariant {
                id: "compose".into(),
                description: "Docker compose project".into(),
                requires_files: vec!["docker-compose.yml".into()],
                requires_directories: vec![],
                requires_commands: vec!["docker".into()],
                steps: vec![step(
                    "compose-logs",
                    "docker compose logs --tail 50",
                    "docker",
                    &["compose", "logs", "--tail", "50"],
                    "current",
                )],
            }],
        ),
        // Local dev
        recipe(
            "ports-list",
            "List listening ports",
            "Show listening TCP ports (macOS lsof)",
            &["dev", "ports"],
            RecipeScope::Global,
            vec![RecipeVariant {
                id: "lsof".into(),
                description: "lsof available".into(),
                requires_files: vec![],
                requires_directories: vec![],
                requires_commands: vec!["lsof".into()],
                steps: vec![step(
                    "lsof-ports",
                    "lsof listening TCP",
                    "lsof",
                    &["-nP", "-iTCP", "-sTCP:LISTEN"],
                    "current",
                )],
            }],
        ),
        recipe(
            "git-root",
            "Git root",
            "Print git repository root",
            &["git", "dev"],
            RecipeScope::CurrentProject,
            vec![git_variant(
                "git-root",
                &["rev-parse", "--show-toplevel"],
                "git root",
            )],
        ),
        recipe(
            "show-env",
            "Show environment",
            "Print env vars (secrets redacted)",
            &["dev", "env"],
            RecipeScope::Global,
            vec![RecipeVariant {
                id: "env".into(),
                description: "Print environment".into(),
                requires_files: vec![],
                requires_directories: vec![],
                requires_commands: vec!["env".into()],
                steps: vec![step(
                    "env",
                    "env (filtered by runner)",
                    "env",
                    &[],
                    "current",
                )],
            }],
        ),
        // Luma repository
        recipe(
            "luma-check",
            "Luma full verification",
            "Formatting, clippy, and tests for Luma",
            &["luma", "rust", "verify"],
            RecipeScope::LumaRepository,
            vec![RecipeVariant {
                id: "luma-rust".into(),
                description: "Luma Rust workspace".into(),
                requires_files: vec!["rust/Cargo.toml".into(), "AGENTS.md".into()],
                requires_directories: vec![],
                requires_commands: vec!["cargo".into()],
                steps: vec![
                    step(
                        "fmt",
                        "cargo fmt",
                        "cargo",
                        &["fmt", "--all", "--", "--check"],
                        "rust",
                    ),
                    step(
                        "clippy",
                        "cargo clippy",
                        "cargo",
                        &[
                            "clippy",
                            "--workspace",
                            "--all-targets",
                            "--all-features",
                            "--",
                            "-D",
                            "warnings",
                        ],
                        "rust",
                    ),
                    step(
                        "test",
                        "cargo test",
                        "cargo",
                        &["test", "--workspace", "--all-features"],
                        "rust",
                    ),
                ],
            }],
        ),
        recipe(
            "luma-test",
            "Luma test",
            "Run Luma workspace tests",
            &["luma", "test"],
            RecipeScope::LumaRepository,
            vec![RecipeVariant {
                id: "luma-rust".into(),
                description: "Luma Rust workspace".into(),
                requires_files: vec!["rust/Cargo.toml".into(), "AGENTS.md".into()],
                requires_directories: vec![],
                requires_commands: vec!["cargo".into()],
                steps: vec![step(
                    "test",
                    "cargo test",
                    "cargo",
                    &["test", "--workspace", "--all-features"],
                    "rust",
                )],
            }],
        ),
        recipe(
            "luma-architecture-check",
            "Luma architecture check",
            "Run architecture allowlist script",
            &["luma", "architecture"],
            RecipeScope::LumaRepository,
            vec![RecipeVariant {
                id: "luma-arch".into(),
                description: "Luma repository".into(),
                requires_files: vec![
                    "rust/scripts/check_architecture.sh".into(),
                    "AGENTS.md".into(),
                ],
                requires_directories: vec![],
                requires_commands: vec!["bash".into()],
                steps: vec![step(
                    "arch-check",
                    "check architecture",
                    "bash",
                    &["scripts/check_architecture.sh"],
                    "rust",
                )],
            }],
        ),
        // Generic test recipe (multi-ecosystem)
        recipe(
            "test",
            "Run project tests",
            "Run the test command appropriate for the current project",
            &["test", "project"],
            RecipeScope::CurrentProject,
            vec![
                RecipeVariant {
                    id: "rust".into(),
                    description: "Rust project".into(),
                    requires_files: vec!["Cargo.toml".into()],
                    requires_directories: vec![],
                    requires_commands: vec!["cargo".into()],
                    steps: vec![step(
                        "cargo-test",
                        "cargo test",
                        "cargo",
                        &["test", "--workspace", "--all-features"],
                        "current",
                    )],
                },
                RecipeVariant {
                    id: "node".into(),
                    description: "Node project".into(),
                    requires_files: vec!["package.json".into()],
                    requires_directories: vec![],
                    requires_commands: vec!["npm".into()],
                    steps: vec![step("npm-test", "npm test", "npm", &["test"], "current")],
                },
                RecipeVariant {
                    id: "python".into(),
                    description: "Python project".into(),
                    requires_files: vec!["pyproject.toml".into()],
                    requires_directories: vec![],
                    requires_commands: vec!["pytest".into()],
                    steps: vec![step("pytest", "pytest", "pytest", &[], "current")],
                },
            ],
        ),
    ]
}
