use luma_domain::{CommandStep, Recipe, RecipeRisk, RecipeScope, RecipeVariant};

fn step(id: &str, label: &str, program: &str, args: &[&str], cwd: &str) -> CommandStep {
    CommandStep {
        id: id.into(),
        label: label.into(),
        program: program.into(),
        args: args.iter().map(|s| (*s).to_string()).collect(),
        cwd: cwd.into(),
        continue_on_error: false,
    }
}

fn git_variants(id: &str, program_args: &[&str], label: &str) -> Vec<RecipeVariant> {
    let repository = RecipeVariant {
        id: id.into(),
        description: "Git repository".into(),
        requires_files: vec![],
        requires_directories: vec![".git".into()],
        requires_commands: vec!["git".into()],
        steps: vec![step(id, label, "git", program_args, "current")],
    };
    let worktree = RecipeVariant {
        id: format!("{id}-worktree"),
        description: "Git worktree".into(),
        requires_files: vec![".git".into()],
        requires_directories: vec![],
        requires_commands: vec!["git".into()],
        steps: vec![step(id, label, "git", program_args, "current")],
    };
    vec![repository, worktree]
}

fn recipe(
    id: &str,
    title: &str,
    description: &str,
    tags: &[&str],
    scope: RecipeScope,
    variants: Vec<RecipeVariant>,
) -> Recipe {
    recipe_with_risk(
        id,
        title,
        description,
        tags,
        scope,
        RecipeRisk::Safe,
        variants,
    )
}

fn recipe_with_risk(
    id: &str,
    title: &str,
    description: &str,
    tags: &[&str],
    scope: RecipeScope,
    risk: RecipeRisk,
    variants: Vec<RecipeVariant>,
) -> Recipe {
    Recipe {
        id: id.into(),
        title: title.into(),
        description: description.into(),
        tags: tags.iter().map(|t| (*t).to_string()).collect(),
        scope,
        target: luma_domain::RecipeTarget::LocalShell,
        group: String::new(),
        risk,
        parameters: vec![],
        variants,
        enabled: true,
    }
}

#[allow(clippy::too_many_arguments)]
fn ssh_remote_recipe(
    id: &str,
    title: &str,
    description: &str,
    group: &str,
    risk: RecipeRisk,
    parameters: Vec<luma_domain::RecipeParameter>,
    program: &str,
    args: &[&str],
) -> Recipe {
    Recipe {
        id: id.into(),
        title: title.into(),
        description: description.into(),
        tags: vec!["ssh".into(), group.to_ascii_lowercase()],
        scope: RecipeScope::SshSession,
        target: luma_domain::RecipeTarget::RemoteShell,
        group: group.into(),
        risk,
        parameters,
        variants: vec![RecipeVariant {
            id: "default".into(),
            description: String::new(),
            requires_files: vec![],
            requires_directories: vec![],
            requires_commands: vec![],
            steps: vec![step(id, title, program, args, "current")],
        }],
        enabled: true,
    }
}

pub fn builtin_recipes() -> Vec<Recipe> {
    vec![
        // Git
        recipe(
            "git-status",
            "Git status",
            "Short branch status",
            &["git"],
            RecipeScope::CurrentProject,
            git_variants(
                "git-status",
                &["status", "--short", "--branch"],
                "git status",
            ),
        ),
        recipe(
            "git-diff",
            "Git diff",
            "Diff stat summary",
            &["git"],
            RecipeScope::CurrentProject,
            git_variants("git-diff", &["diff", "--stat"], "git diff --stat"),
        ),
        recipe(
            "git-log",
            "Git log",
            "Recent commits oneline",
            &["git"],
            RecipeScope::CurrentProject,
            git_variants("git-log", &["log", "--oneline", "-10"], "git log"),
        ),
        recipe(
            "git-branch",
            "Git branch",
            "Show current branch",
            &["git"],
            RecipeScope::CurrentProject,
            git_variants("git-branch", &["branch", "--show-current"], "git branch"),
        ),
        recipe(
            "git-worktree",
            "Git worktree",
            "List worktrees",
            &["git"],
            RecipeScope::CurrentProject,
            git_variants("git-worktree", &["worktree", "list"], "git worktree list"),
        ),
        // Rust
        recipe(
            "rust-fmt-check",
            "Rust fmt check",
            "Check formatting with cargo fmt",
            &["rust", "fmt"],
            RecipeScope::CurrentProject,
            vec![RecipeVariant {
                id: "rust".into(),
                description: "Rust project".into(),
                requires_files: vec!["Cargo.toml".into()],
                requires_directories: vec![],
                requires_commands: vec!["cargo".into()],
                steps: vec![step(
                    "cargo-fmt",
                    "cargo fmt --check",
                    "cargo",
                    &["fmt", "--all", "--", "--check"],
                    "current",
                )],
            }],
        ),
        recipe(
            "rust-check",
            "Rust check",
            "cargo check workspace",
            &["rust", "check"],
            RecipeScope::CurrentProject,
            vec![RecipeVariant {
                id: "rust".into(),
                description: "Rust project".into(),
                requires_files: vec!["Cargo.toml".into()],
                requires_directories: vec![],
                requires_commands: vec!["cargo".into()],
                steps: vec![step(
                    "cargo-check",
                    "cargo check",
                    "cargo",
                    &["check", "--workspace", "--all-features"],
                    "current",
                )],
            }],
        ),
        recipe(
            "rust-test",
            "Rust test",
            "Run cargo test",
            &["rust", "test"],
            RecipeScope::CurrentProject,
            vec![RecipeVariant {
                id: "rust".into(),
                description: "Rust project".into(),
                requires_files: vec!["Cargo.toml".into()],
                requires_directories: vec![],
                requires_commands: vec!["cargo".into()],
                steps: vec![step(
                    "cargo-test",
                    "cargo test",
                    "cargo",
                    &["test", "--workspace", "--all-features"],
                    "current",
                )],
            }],
        ),
        recipe(
            "rust-clippy",
            "Rust clippy",
            "Run cargo clippy with warnings denied",
            &["rust", "clippy"],
            RecipeScope::CurrentProject,
            vec![RecipeVariant {
                id: "rust".into(),
                description: "Rust project".into(),
                requires_files: vec!["Cargo.toml".into()],
                requires_directories: vec![],
                requires_commands: vec!["cargo".into()],
                steps: vec![step(
                    "cargo-clippy",
                    "cargo clippy",
                    "cargo",
                    &[
                        "clippy",
                        "--workspace",
                        "--all-targets",
                        "--all-features",
                        "--",
                        "-D",
                        "warnings",
                    ],
                    "current",
                )],
            }],
        ),
        // Node
        recipe(
            "node-test",
            "Node test",
            "npm test",
            &["node", "test"],
            RecipeScope::CurrentProject,
            vec![RecipeVariant {
                id: "node".into(),
                description: "Node project".into(),
                requires_files: vec!["package.json".into()],
                requires_directories: vec![],
                requires_commands: vec!["npm".into()],
                steps: vec![step("npm-test", "npm test", "npm", &["test"], "current")],
            }],
        ),
        recipe(
            "node-lint",
            "Node lint",
            "npm run lint when available",
            &["node", "lint"],
            RecipeScope::CurrentProject,
            vec![RecipeVariant {
                id: "node".into(),
                description: "Node project".into(),
                requires_files: vec!["package.json".into()],
                requires_directories: vec![],
                requires_commands: vec!["npm".into()],
                steps: vec![step(
                    "npm-lint",
                    "npm run lint",
                    "npm",
                    &["run", "lint"],
                    "current",
                )],
            }],
        ),
        recipe(
            "node-build",
            "Node build",
            "npm run build",
            &["node", "build"],
            RecipeScope::CurrentProject,
            vec![RecipeVariant {
                id: "node".into(),
                description: "Node project".into(),
                requires_files: vec!["package.json".into()],
                requires_directories: vec![],
                requires_commands: vec!["npm".into()],
                steps: vec![step(
                    "npm-build",
                    "npm run build",
                    "npm",
                    &["run", "build"],
                    "current",
                )],
            }],
        ),
        // Python
        recipe(
            "python-test",
            "Python test",
            "Run pytest",
            &["python", "test"],
            RecipeScope::CurrentProject,
            vec![
                RecipeVariant {
                    id: "pytest-pyproject".into(),
                    description: "Python pyproject".into(),
                    requires_files: vec!["pyproject.toml".into()],
                    requires_directories: vec![],
                    requires_commands: vec!["pytest".into()],
                    steps: vec![step("pytest", "pytest", "pytest", &[], "current")],
                },
                RecipeVariant {
                    id: "pytest-ini".into(),
                    description: "pytest.ini project".into(),
                    requires_files: vec!["pytest.ini".into()],
                    requires_directories: vec![],
                    requires_commands: vec!["pytest".into()],
                    steps: vec![step("pytest", "pytest", "pytest", &[], "current")],
                },
            ],
        ),
        recipe(
            "python-lint",
            "Python lint",
            "Run ruff check",
            &["python", "lint"],
            RecipeScope::CurrentProject,
            vec![RecipeVariant {
                id: "ruff".into(),
                description: "Python with ruff".into(),
                requires_files: vec!["pyproject.toml".into()],
                requires_directories: vec![],
                requires_commands: vec!["ruff".into()],
                steps: vec![step(
                    "ruff-check",
                    "ruff check",
                    "ruff",
                    &["check"],
                    "current",
                )],
            }],
        ),
        // Docker
        recipe(
            "docker-ps",
            "Docker ps",
            "List running containers",
            &["docker"],
            RecipeScope::Global,
            vec![RecipeVariant {
                id: "docker".into(),
                description: "Docker available".into(),
                requires_files: vec![],
                requires_directories: vec![],
                requires_commands: vec!["docker".into()],
                steps: vec![step("docker-ps", "docker ps", "docker", &["ps"], "current")],
            }],
        ),
        recipe(
            "docker-compose-ps",
            "Docker compose ps",
            "List compose services",
            &["docker", "compose"],
            RecipeScope::CurrentProject,
            vec![RecipeVariant {
                id: "compose".into(),
                description: "Docker compose project".into(),
                requires_files: vec!["docker-compose.yml".into()],
                requires_directories: vec![],
                requires_commands: vec!["docker".into()],
                steps: vec![step(
                    "compose-ps",
                    "docker compose ps",
                    "docker",
                    &["compose", "ps"],
                    "current",
                )],
            }],
        ),
        recipe(
            "docker-compose-logs",
            "Docker compose logs",
            "Tail compose logs",
            &["docker", "compose", "logs"],
            RecipeScope::CurrentProject,
            vec![RecipeVariant {
                id: "compose".into(),
                description: "Docker compose project".into(),
                requires_files: vec!["docker-compose.yml".into()],
                requires_directories: vec![],
                requires_commands: vec!["docker".into()],
                steps: vec![step(
                    "compose-logs",
                    "docker compose logs --tail 50",
                    "docker",
                    &["compose", "logs", "--tail", "50"],
                    "current",
                )],
            }],
        ),
        // Local dev
        recipe(
            "ports-list",
            "List listening ports",
            "Show listening TCP ports (macOS lsof)",
            &["dev", "ports"],
            RecipeScope::Global,
            vec![RecipeVariant {
                id: "lsof".into(),
                description: "lsof available".into(),
                requires_files: vec![],
                requires_directories: vec![],
                requires_commands: vec!["lsof".into()],
                steps: vec![step(
                    "lsof-ports",
                    "lsof listening TCP",
                    "lsof",
                    &["-nP", "-iTCP", "-sTCP:LISTEN"],
                    "current",
                )],
            }],
        ),
        recipe(
            "git-root",
            "Git root",
            "Print git repository root",
            &["git", "dev"],
            RecipeScope::CurrentProject,
            git_variants("git-root", &["rev-parse", "--show-toplevel"], "git root"),
        ),
        recipe_with_risk(
            "show-env",
            "Show environment",
            "Print env vars (secrets redacted)",
            &["dev", "env"],
            RecipeScope::Global,
            RecipeRisk::Confirm,
            vec![RecipeVariant {
                id: "env".into(),
                description: "Print environment".into(),
                requires_files: vec![],
                requires_directories: vec![],
                requires_commands: vec!["env".into()],
                steps: vec![step(
                    "env",
                    "env (filtered by runner)",
                    "env",
                    &[],
                    "current",
                )],
            }],
        ),
        // Luma repository
        recipe(
            "luma-check",
            "Luma full verification",
            "Formatting, clippy, and tests for Luma",
            &["luma", "rust", "verify"],
            RecipeScope::LumaRepository,
            vec![RecipeVariant {
                id: "luma-rust".into(),
                description: "Luma Rust workspace".into(),
                requires_files: vec!["rust/Cargo.toml".into(), "AGENTS.md".into()],
                requires_directories: vec![],
                requires_commands: vec!["cargo".into()],
                steps: vec![
                    step(
                        "fmt",
                        "cargo fmt",
                        "cargo",
                        &["fmt", "--all", "--", "--check"],
                        "rust",
                    ),
                    step(
                        "clippy",
                        "cargo clippy",
                        "cargo",
                        &[
                            "clippy",
                            "--workspace",
                            "--all-targets",
                            "--all-features",
                            "--",
                            "-D",
                            "warnings",
                        ],
                        "rust",
                    ),
                    step(
                        "test",
                        "cargo test",
                        "cargo",
                        &["test", "--workspace", "--all-features"],
                        "rust",
                    ),
                ],
            }],
        ),
        recipe(
            "luma-test",
            "Luma test",
            "Run Luma workspace tests",
            &["luma", "test"],
            RecipeScope::LumaRepository,
            vec![RecipeVariant {
                id: "luma-rust".into(),
                description: "Luma Rust workspace".into(),
                requires_files: vec!["rust/Cargo.toml".into(), "AGENTS.md".into()],
                requires_directories: vec![],
                requires_commands: vec!["cargo".into()],
                steps: vec![step(
                    "test",
                    "cargo test",
                    "cargo",
                    &["test", "--workspace", "--all-features"],
                    "rust",
                )],
            }],
        ),
        recipe(
            "luma-architecture-check",
            "Luma architecture check",
            "Run architecture allowlist script",
            &["luma", "architecture"],
            RecipeScope::LumaRepository,
            vec![RecipeVariant {
                id: "luma-arch".into(),
                description: "Luma repository".into(),
                requires_files: vec![
                    "rust/scripts/check_architecture.sh".into(),
                    "AGENTS.md".into(),
                ],
                requires_directories: vec![],
                requires_commands: vec!["bash".into()],
                steps: vec![step(
                    "arch-check",
                    "check architecture",
                    "bash",
                    &["scripts/check_architecture.sh"],
                    "rust",
                )],
            }],
        ),
        // Generic test recipe (multi-ecosystem)
        recipe(
            "test",
            "Run project tests",
            "Run the test command appropriate for the current project",
            &["test", "project"],
            RecipeScope::CurrentProject,
            vec![
                RecipeVariant {
                    id: "rust".into(),
                    description: "Rust project".into(),
                    requires_files: vec!["Cargo.toml".into()],
                    requires_directories: vec![],
                    requires_commands: vec!["cargo".into()],
                    steps: vec![step(
                        "cargo-test",
                        "cargo test",
                        "cargo",
                        &["test", "--workspace", "--all-features"],
                        "current",
                    )],
                },
                RecipeVariant {
                    id: "node".into(),
                    description: "Node project".into(),
                    requires_files: vec!["package.json".into()],
                    requires_directories: vec![],
                    requires_commands: vec!["npm".into()],
                    steps: vec![step("npm-test", "npm test", "npm", &["test"], "current")],
                },
                RecipeVariant {
                    id: "python".into(),
                    description: "Python project".into(),
                    requires_files: vec!["pyproject.toml".into()],
                    requires_directories: vec![],
                    requires_commands: vec!["pytest".into()],
                    steps: vec![step("pytest", "pytest", "pytest", &[], "current")],
                },
            ],
        ),
        // SSH Workspace remote shelf (Copy/Insert only)
        ssh_remote_recipe(
            "ssh-uptime",
            "uptime",
            "Show system uptime",
            "System",
            RecipeRisk::Safe,
            vec![],
            "uptime",
            &[],
        ),
        ssh_remote_recipe(
            "ssh-df",
            "df -h",
            "Disk free space",
            "System",
            RecipeRisk::Safe,
            vec![],
            "df",
            &["-h"],
        ),
        ssh_remote_recipe(
            "ssh-free",
            "free -h",
            "Memory usage",
            "System",
            RecipeRisk::Safe,
            vec![],
            "free",
            &["-h"],
        ),
        ssh_remote_recipe(
            "ssh-ps-mem",
            "ps aux --sort=-%mem",
            "Processes by memory",
            "System",
            RecipeRisk::Safe,
            vec![],
            "ps",
            &["aux", "--sort=-%mem"],
        ),
        ssh_remote_recipe(
            "ssh-journalctl",
            "journalctl service logs",
            "Recent journal logs for a unit",
            "System",
            RecipeRisk::Safe,
            vec![
                param_text("service", "服务名", true, None),
                param_integer("lines", "日志行数", Some("100"), 1, 10000),
            ],
            "journalctl",
            &["-u", "${service}", "-n", "${lines}", "--no-pager"],
        ),
        ssh_remote_recipe(
            "ssh-systemctl-status",
            "systemctl status",
            "Service status",
            "System",
            RecipeRisk::Safe,
            vec![param_text("service", "服务名", true, None)],
            "systemctl",
            &["status", "${service}"],
        ),
        ssh_remote_recipe(
            "ssh-tail",
            "tail file",
            "Tail a file",
            "System",
            RecipeRisk::Safe,
            vec![
                param_integer("lines", "行数", Some("100"), 1, 10000),
                param_path("path", "文件路径", true, None),
            ],
            "tail",
            &["-n", "${lines}", "${path}"],
        ),
        ssh_remote_recipe(
            "ssh-docker-ps",
            "docker ps",
            "List running containers",
            "Docker",
            RecipeRisk::Safe,
            vec![],
            "docker",
            &["ps"],
        ),
        ssh_remote_recipe(
            "ssh-docker-ps-a",
            "docker ps -a",
            "List all containers",
            "Docker",
            RecipeRisk::Safe,
            vec![],
            "docker",
            &["ps", "-a"],
        ),
        ssh_remote_recipe(
            "ssh-docker-stats",
            "docker stats",
            "Container stats snapshot",
            "Docker",
            RecipeRisk::Safe,
            vec![],
            "docker",
            &["stats", "--no-stream"],
        ),
        ssh_remote_recipe(
            "ssh-docker-logs",
            "docker logs",
            "Container logs",
            "Docker",
            RecipeRisk::Safe,
            vec![
                param_text("container", "容器名称", true, None),
                param_integer("lines", "日志行数", Some("100"), 1, 10000),
            ],
            "docker",
            &["logs", "--tail", "${lines}", "${container}"],
        ),
        ssh_remote_recipe(
            "ssh-docker-inspect",
            "docker inspect",
            "Inspect a container",
            "Docker",
            RecipeRisk::Safe,
            vec![param_text("container", "容器名称", true, None)],
            "docker",
            &["inspect", "${container}"],
        ),
        ssh_remote_recipe(
            "ssh-docker-exec",
            "docker exec -it",
            "Exec into a container",
            "Docker",
            RecipeRisk::Confirm,
            vec![
                param_text("container", "容器名称", true, None),
                param_text("shell", "Shell", false, Some("sh")),
            ],
            "docker",
            &["exec", "-it", "${container}", "${shell}"],
        ),
        ssh_remote_recipe(
            "ssh-docker-compose-ps",
            "docker compose ps",
            "Compose services",
            "Docker",
            RecipeRisk::Safe,
            vec![],
            "docker",
            &["compose", "ps"],
        ),
        ssh_remote_recipe(
            "ssh-docker-compose-logs",
            "docker compose logs",
            "Compose service logs",
            "Docker",
            RecipeRisk::Safe,
            vec![
                param_text("service", "服务名", false, Some("")),
                param_integer("lines", "日志行数", Some("100"), 1, 10000),
            ],
            "docker",
            &["compose", "logs", "--tail", "${lines}", "${service}"],
        ),
        ssh_remote_recipe(
            "ssh-docker-compose-restart",
            "docker compose restart",
            "Restart a compose service",
            "Docker",
            RecipeRisk::Destructive,
            vec![param_text("service", "服务名", true, None)],
            "docker",
            &["compose", "restart", "${service}"],
        ),
    ]
}

fn param_text(
    id: &str,
    label: &str,
    required: bool,
    default: Option<&str>,
) -> luma_domain::RecipeParameter {
    luma_domain::RecipeParameter {
        id: id.into(),
        label: label.into(),
        description: String::new(),
        kind: luma_domain::RecipeParameterKind::Text,
        required,
        default: default.map(str::to_string),
        choices: vec![],
        min: None,
        max: None,
        pattern: None,
        max_length: Some(256),
    }
}

fn param_integer(
    id: &str,
    label: &str,
    default: Option<&str>,
    min: i64,
    max: i64,
) -> luma_domain::RecipeParameter {
    luma_domain::RecipeParameter {
        id: id.into(),
        label: label.into(),
        description: String::new(),
        kind: luma_domain::RecipeParameterKind::Integer,
        required: false,
        default: default.map(str::to_string),
        choices: vec![],
        min: Some(min),
        max: Some(max),
        pattern: None,
        max_length: None,
    }
}

fn param_path(
    id: &str,
    label: &str,
    required: bool,
    default: Option<&str>,
) -> luma_domain::RecipeParameter {
    luma_domain::RecipeParameter {
        id: id.into(),
        label: label.into(),
        description: String::new(),
        kind: luma_domain::RecipeParameterKind::Path,
        required,
        default: default.map(str::to_string),
        choices: vec![],
        min: None,
        max: None,
        pattern: None,
        max_length: Some(1024),
    }
}
